# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed 4 million,
# find the sum of even-valued terms.

a = 1
b = 2
c = 0
total =0
while c < 4000000:
    c = a + b
    if b % 2 == 0:
        total = b + total
    a = b
    b = c
    print("C is ",c)
print (total)